Password generator
abdallahsow/scrimba-js-solo-projects pull request #2
Opened 2022-08-11 08:43 UTC by abdallahsow

2022-08-11 11:52 UTC, abdallahsow commented
![Screenshot 2022-08-11 144048](https://user-images.githubusercontent.com/108878701/184126799-c646dd69-bcf2-48e4-845c-00bbf7cfc48f.png)
![Screenshot 2022-08-11 144309](https://user-images.githubusercontent.com/108878701/184126851-b35a2b08-639b-4192-b4c2-39f3b59b9bc3.png)
[https://www.figma.com/file/UVE3N1z7amtrIN3bVhM7Vl/Random-Password-Generator-(New-version)-(Copy)?node-id=102%3A702](url)

I have joined the requirements of the project and the stretch goals  requested from Scrimba ( meant for people who get bored or thinks JS is too simple which I don't :sweat_smile: , a kind of challenge)
And of course the link of the figma design for you to be able to check the HTML & CSS

2022-08-15 08:22 UTC, ahamad-ch requested changes

2022-08-15 08:22 UTC, ahamad-ch commented on Password Generator/index.css
> +}
- [ ] Create classnames for each of the elements fr which the styles are applied directly.

2022-08-15 08:22 UTC, ahamad-ch commented on Password Generator/index.css
> +rect {
- [ ] Same here. Create classname and apply css appropriately.

2022-08-15 08:22 UTC, ahamad-ch commented on Password Generator/index.js
> +let characters = [
- [ ] Use a regular expression for this one instead of an array of all characters.

2022-08-15 08:22 UTC, ahamad-ch commented on Password Generator/index.js
> +    secondPass.textContent += randomTwoPass;
- [ ] The first and second passwords are the same. Update it
![image](https://user-images.githubusercontent.com/73190890/184601418-e498ede9-e639-4f24-aaab-a0e33081b253.png)

2022-08-23 13:26 UTC, merged