Unit converter
abdallahsow/scrimba-js-solo-projects pull request #3
Opened 2022-08-16 08:24 UTC by abdallahsow

2022-08-17 19:43 UTC, abdallahsow commented
[https://www.figma.com/file/JxMP4NYqNNtvNdljBnyrja/Unit-Conversion-(Copy)?node-id=0%3A13](url)

2022-08-23 13:33 UTC, ahamad-ch requested changes
- [ ] Make sure to apply a maxlength for this input field and let the input field have a fixed width as its overflowing
![image](https://user-images.githubusercontent.com/73190890/186171537-a5ed2970-cddb-433f-8ec6-4751ca0113f9.png)

2022-08-23 13:33 UTC, ahamad-ch commented on Unit-converter/style.css
> +  gap: 70px;
- [ ] apply `justify-content: center;`

2022-08-28 18:33 UTC, ahamad-ch requested changes
- [ ] Fix the merge conflicts

2022-09-29 06:44 UTC, merged